# Generated by Django 5.1.1 on 2025-03-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeserieslayer',
            name='category',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
