# Generated by Django 5.1.1 on 2025-04-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0003_county_maplayer_county_timeserieslayer_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeserieslayer',
            options={'ordering': ['-name']},
        ),
    ]
