# Generated by Django 5.1.1 on 2025-04-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0005_alter_timeserieslayer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeserieslayer',
            options={'ordering': ['month']},
        ),
    ]
