# Generated by Django 5.1.1 on 2025-04-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0006_alter_timeserieslayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='description',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='timeserieslayer',
            name='description',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
