# Generated by Django 5.1.1 on 2025-04-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0007_maplayer_description_timeserieslayer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timeserieslayer',
            name='description',
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapdatacontroler.categorydescription'),
        ),
        migrations.AlterField(
            model_name='timeserieslayer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapdatacontroler.categorydescription'),
        ),
    ]
