# Generated by Django 5.1.1 on 2025-04-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0008_categorydescription_remove_maplayer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='category_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapdatacontroler.categorydescription'),
        ),
        migrations.AddField(
            model_name='timeserieslayer',
            name='category_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapdatacontroler.categorydescription'),
        ),
        migrations.AlterField(
            model_name='categorydescription',
            name='category',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timeserieslayer',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
