# Generated by Django 5.1.1 on 2025-04-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0009_maplayer_category_fk_timeserieslayer_category_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='category_fk',
        ),
        migrations.RemoveField(
            model_name='timeserieslayer',
            name='category_fk',
        ),
    ]
