# Generated by Django 5.1.1 on 2025-04-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0010_remove_maplayer_category_fk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydescription',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='timeserieslayer',
            name='category_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapdatacontroler.categorydescription'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='timeserieslayer',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
