# Generated by Django 5.1.1 on 2025-04-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0011_rename_category_categorydescription_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='category_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapdatacontroler.categorydescription'),
        ),
    ]
