# Generated by Django 5.1.1 on 2025-04-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0012_maplayer_category_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='timeserieslayer',
            name='category',
        ),
    ]
