# Generated by Django 5.1.1 on 2025-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0016_notebook_alter_categorydescription_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='maplayer',
            name='has_wfs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='type',
            field=models.CharField(choices=[('WFS', 'WMS')], default='WMS', max_length=50),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='timeserieslayer',
            name='has_wfs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeserieslayer',
            name='type',
            field=models.CharField(choices=[('WFS', 'WMS')], default='WMS', max_length=50),
        ),
    ]
