# Generated by Django 5.1.1 on 2025-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdatacontroler', '0017_alter_maplayer_options_maplayer_has_wfs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='type',
            field=models.CharField(choices=[('WFS', 'WFS'), ('WMS', 'WMS')], default='WMS', max_length=50),
        ),
        migrations.AlterField(
            model_name='timeserieslayer',
            name='type',
            field=models.CharField(choices=[('WFS', 'WFS'), ('WMS', 'WMS')], default='WMS', max_length=50),
        ),
    ]
