version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles  # Mount static files
      - ./media:/app/media  # Mount media files
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  # Optionally, you can add a database service (e.g., PostgreSQL) if you want
  # db:
  #   image: postgres:13
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: your_db_name
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password
